"""initial schema

Revision ID: c6a296383dbf
Revises: 
Create Date: 2026-07-03 22:03:47.945367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a296383dbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('version_tag', sa.String(length=64), nullable=False),
    sa.Column('trained_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=True),
    sa.Column('training_data_hash', sa.String(length=64), nullable=True),
    sa.Column('c_index', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('brier_score_90d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ph_test_pvalue', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('contamination_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_tag')
    )
    op.create_table('score_run_metadata',
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('transformers_scored', sa.Integer(), nullable=False),
    sa.Column('transformers_failed', sa.Integer(), nullable=False),
    sa.Column('newly_critical', sa.Integer(), nullable=True),
    sa.Column('newly_high', sa.Integer(), nullable=True),
    sa.Column('newly_healthy', sa.Integer(), nullable=True),
    sa.Column('avg_score_delta', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ml_mode', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substations',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('voltage_kv', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_substations_location', 'substations', ['location'], unique=False, postgresql_using='gist')
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeders',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('substation_id', sa.UUID(), nullable=False),
    sa.Column('voltage_kv', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('feeder_type', sa.String(length=32), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dedup_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_table('transformers',
    sa.Column('transformer_code', sa.String(length=64), nullable=False),
    sa.Column('feeder_id', sa.UUID(), nullable=True),
    sa.Column('substation_id', sa.UUID(), nullable=True),
    sa.Column('rated_kva', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('voltage_hv_kv', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('voltage_lv_v', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('installation_type', sa.String(length=32), nullable=True),
    sa.Column('cooling_type', sa.String(length=16), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('block', sa.String(length=64), nullable=True),
    sa.Column('is_flood_prone', sa.Boolean(), nullable=True),
    sa.Column('is_high_lightning', sa.Boolean(), nullable=True),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('last_oil_test_date', sa.Date(), nullable=True),
    sa.Column('commissioning_date', sa.Date(), nullable=True),
    sa.Column('num_consumers', sa.Integer(), nullable=False),
    sa.Column('consumer_category', sa.String(length=32), nullable=True),
    sa.Column('area_criticality', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('operational_status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transformer_code')
    )
    op.create_index('idx_transformers_location', 'transformers', ['location'], unique=False, postgresql_using='gist')
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transformer_id', sa.UUID(), nullable=False),
    sa.Column('complaint_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolution_time_hrs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_events',
    sa.Column('transformer_id', sa.UUID(), nullable=False),
    sa.Column('failure_date', sa.DateTime(), nullable=False),
    sa.Column('failure_type', sa.String(length=64), nullable=True),
    sa.Column('outage_duration_hrs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('consumers_affected', sa.Integer(), nullable=True),
    sa.Column('cause_identified', sa.Boolean(), nullable=True),
    sa.Column('cause_description', sa.Text(), nullable=True),
    sa.Column('restoration_date', sa.DateTime(), nullable=True),
    sa.Column('replacement_cost_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reported_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_readings',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transformer_id', sa.UUID(), nullable=False),
    sa.Column('load_kw', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('load_kvar', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('load_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('voltage_lv', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('current_a', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperature_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'transformer_id')
    )
    op.create_table('maintenance_logs',
    sa.Column('transformer_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('maintenance_type', sa.String(length=32), nullable=False),
    sa.Column('components_replaced', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('oil_bdv_kv', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('winding_resistance', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('insulation_megohm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('engineer_id', sa.UUID(), nullable=True),
    sa.Column('crew_size', sa.Integer(), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('next_maintenance_due', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transformer_scores',
    sa.Column('transformer_id', sa.UUID(), nullable=False),
    sa.Column('score_run_id', sa.UUID(), nullable=True),
    sa.Column('survival_prob_30d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('survival_prob_60d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('survival_prob_90d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.Column('failure_risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['score_run_id'], ['score_run_metadata.id'], ),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shap_explanations',
    sa.Column('transformer_id', sa.UUID(), nullable=False),
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('top_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['transformer_scores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shap_explanations')
    op.drop_table('transformer_scores')
    op.drop_table('maintenance_logs')
    op.drop_table('load_readings')
    op.drop_table('failure_events')
    op.drop_table('complaints')
    op.drop_index('idx_transformers_location', table_name='transformers', postgresql_using='gist')
    op.drop_table('transformers')
    op.drop_table('notifications')
    op.drop_table('feeders')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('idx_substations_location', table_name='substations', postgresql_using='gist')
    op.drop_table('substations')
    op.drop_table('score_run_metadata')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
